name: 💡 Feature Request
description: Suggest a new feature or improvement for FlowWatcher
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Have an idea to make FlowWatcher better? We'd love to hear it!

  - type: textarea
    id: problem
    attributes:
      label: Problem Description
      description: What problem does this feature solve? Is it related to a frustration?
      placeholder: "I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
    validations:
      required: false

  - type: dropdown
    id: area
    attributes:
      label: Feature Area
      description: Which part of FlowWatcher does this relate to?
      options:
        - Dashboard / Monitoring UI
        - Network monitoring engine
        - Process-based monitoring
        - Action execution (shutdown, sleep, etc.)
        - Settings / Configuration
        - System tray / background operation
        - Activity logs
        - Internationalization / translations
        - Performance
        - Other
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other information, mockups, or screenshots.
    validations:
      required: false
